// Auto-generated by analysis/analysis.py — do not edit by hand
const SALES_DATA = {
  "headline": {
    "total_revenue": 2733907117,
    "total_orders": 572112,
    "total_units": 709285,
    "aov": 4779,
    "festival_revenue_share_pct": 31.1,
    "yoy_growth_pct": 14.3
  },
  "monthly": [
    {
      "month": "2023-01",
      "revenue": 114722577,
      "orders": 22409
    },
    {
      "month": "2023-02",
      "revenue": 75291687,
      "orders": 14900
    },
    {
      "month": "2023-03",
      "revenue": 96546498,
      "orders": 19460
    },
    {
      "month": "2023-04",
      "revenue": 81778260,
      "orders": 16538
    },
    {
      "month": "2023-05",
      "revenue": 105249556,
      "orders": 20319
    },
    {
      "month": "2023-06",
      "revenue": 84710905,
      "orders": 16767
    },
    {
      "month": "2023-07",
      "revenue": 93076113,
      "orders": 17634
    },
    {
      "month": "2023-08",
      "revenue": 110862398,
      "orders": 23164
    },
    {
      "month": "2023-09",
      "revenue": 88575913,
      "orders": 17359
    },
    {
      "month": "2023-10",
      "revenue": 166879164,
      "orders": 40828
    },
    {
      "month": "2023-11",
      "revenue": 146777499,
      "orders": 34282
    },
    {
      "month": "2023-12",
      "revenue": 111492420,
      "orders": 22693
    },
    {
      "month": "2024-01",
      "revenue": 125513878,
      "orders": 25176
    },
    {
      "month": "2024-02",
      "revenue": 87255122,
      "orders": 17414
    },
    {
      "month": "2024-03",
      "revenue": 117688482,
      "orders": 22011
    },
    {
      "month": "2024-04",
      "revenue": 95908675,
      "orders": 18428
    },
    {
      "month": "2024-05",
      "revenue": 116917197,
      "orders": 22528
    },
    {
      "month": "2024-06",
      "revenue": 96337174,
      "orders": 18754
    },
    {
      "month": "2024-07",
      "revenue": 99442337,
      "orders": 19345
    },
    {
      "month": "2024-08",
      "revenue": 132570476,
      "orders": 26694
    },
    {
      "month": "2024-09",
      "revenue": 100518831,
      "orders": 19251
    },
    {
      "month": "2024-10",
      "revenue": 233720207,
      "orders": 62983
    },
    {
      "month": "2024-11",
      "revenue": 117922567,
      "orders": 26243
    },
    {
      "month": "2024-12",
      "revenue": 134149182,
      "orders": 26932
    }
  ],
  "festival_vs_normal": {
    "Normal": {
      "days": 621,
      "revenue": 1883826055,
      "revenue_per_day": 3033536,
      "avg_discount": 10.0,
      "return_rate_pct": 2.6
    },
    "Festival": {
      "days": 110,
      "revenue": 850081063,
      "revenue_per_day": 7728010,
      "avg_discount": 34.4,
      "return_rate_pct": 6.1
    }
  },
  "by_festival": [
    {
      "name": "Big Billion Days / Great Indian Festival",
      "revenue": 209306027,
      "orders": 63802,
      "avg_discount": 52.1
    },
    {
      "name": "Diwali Sale",
      "revenue": 155625662,
      "orders": 40532,
      "avg_discount": 45.0
    },
    {
      "name": "Republic Day Sale",
      "revenue": 104502294,
      "orders": 20847,
      "avg_discount": 30.0
    },
    {
      "name": "Independence Day Sale",
      "revenue": 92754043,
      "orders": 20605,
      "avg_discount": 32.8
    },
    {
      "name": "Year End Sale",
      "revenue": 84933980,
      "orders": 17894,
      "avg_discount": 29.5
    },
    {
      "name": "Summer Sale",
      "revenue": 84470117,
      "orders": 16118,
      "avg_discount": 23.5
    },
    {
      "name": "Holi Sale",
      "revenue": 67417942,
      "orders": 13265,
      "avg_discount": 24.1
    },
    {
      "name": "Black Friday / Cyber Monday",
      "revenue": 51070999,
      "orders": 11622,
      "avg_discount": 35.1
    }
  ],
  "by_category": [
    {
      "category": "Mobiles",
      "revenue": 2076542414,
      "orders": 146369,
      "festival_share_pct": 31.1
    },
    {
      "category": "Electronics",
      "revenue": 379063023,
      "orders": 121463,
      "festival_share_pct": 31.2
    },
    {
      "category": "Home & Kitchen",
      "revenue": 98947507,
      "orders": 72544,
      "festival_share_pct": 30.6
    },
    {
      "category": "Fashion",
      "revenue": 75462397,
      "orders": 81458,
      "festival_share_pct": 31.4
    },
    {
      "category": "Sports & Fitness",
      "revenue": 53739732,
      "orders": 50262,
      "festival_share_pct": 31.3
    },
    {
      "category": "Beauty & Personal Care",
      "revenue": 28688179,
      "orders": 45495,
      "festival_share_pct": 31.2
    },
    {
      "category": "Grocery",
      "revenue": 13104456,
      "orders": 31801,
      "festival_share_pct": 30.9
    },
    {
      "category": "Books",
      "revenue": 8359410,
      "orders": 22720,
      "festival_share_pct": 30.4
    }
  ],
  "by_platform": [
    {
      "platform": "Amazon",
      "revenue": 1363914024,
      "orders": 284856,
      "avg_discount": 13.7
    },
    {
      "platform": "Flipkart",
      "revenue": 1369993094,
      "orders": 287256,
      "avg_discount": 13.7
    }
  ],
  "by_weekday": [
    {
      "weekday": "Monday",
      "revenue": 374809004
    },
    {
      "weekday": "Tuesday",
      "revenue": 363008150
    },
    {
      "weekday": "Wednesday",
      "revenue": 368161967
    },
    {
      "weekday": "Thursday",
      "revenue": 354982646
    },
    {
      "weekday": "Friday",
      "revenue": 380477169
    },
    {
      "weekday": "Saturday",
      "revenue": 444432071
    },
    {
      "weekday": "Sunday",
      "revenue": 448036110
    }
  ]
};
